### ISSUE TITLE
Add auto-update to get new releases automatically

### ISSUE THREAD

**Issue by stefanjudis** [stefanjudis/netlify-menubar#5]

**Comment by stefanjudis** [comment]
Fixed. 🎉

**Comment by tmhn** [comment]
Hi Stefan, I've got the 1.2.2 version from the Releases page, having downloaded the latest dmg. Does this version have the support of auto-update? 😄

**Comment by stefanjudis** [comment]
Hey @tmhn, yeah it should. Currently, the app only checks for new releases when it's started though (I think...).

Could you verify that when you quit it and start it again that at some point a notification pops up?

This surely can be improved in the future to check every hour or something. 😊

**Comment by tmhn** [comment]
Hey @stefanjudis In the end I installed the latest .dmg from the releases page and it seems all good!

**Comment by stefanjudis** [comment]
> it seems all good!

Can you specify what this means? So it didn't auto-update? :(

**Comment by tmhn** [comment]
Sorry @stefanjudis I meant to say that since manually updating to the latest version (at the time I updated it was 1.2.3) I then (this morning) saw an update in my MacBook's sidebar/notifications to inform me there's an update for netlify-menubar. It looks to be working as expected! Sorry for any confusion

**Comment by stefanjudis** [comment]
That's great news though... 🎉

I may improve this in the future so that there is a new menu item after the notification appeared "Update now"... but let's see. :)
